#!/bin/bash

if [ $# -lt 1 ]; then
  echo $0 host app_name
  exit 1 
fi

if [ $# -lt 2 ]; then 
 ssh $1 epmd -names
 echo "now run $0 $1 app_port"
 echo "make sure that remote node runs with -name (not -sname)"
 echo "and the name is with full domain of the host."
 exit 0
fi

HOST=$1
APP=$2

PORT=$(ssh $HOST epmd -names| grep "name $2 at port" |cut -f 5 -d ' ')
if [ ! -n "$PORT" ]; then echo "Can't figure out port for $APP"; exit 1; fi
echo "$APP distributed port is $PORT"

BEAM=$(ssh $HOST ps awux |  grep -- "beam.*-name $APP")

# echo $BEAM

COOKIE_ARGS=$(echo $BEAM | sed -n 's/.*-setcookie \([^ ]*\).*/--cookie \1/p')
DOMAIN=$(echo $BEAM | sed -n 's/.*-name [^@]*@\([^ ]*\).*/\1/p')

if [ ! -n "$COOKIE_ARGS" ]; then echo "Can't figure out cookie  for $APP"; exit 1; fi

echo 1. Put into /etc/hosts:
echo 127.0.0.1 $DOMAIN
echo
echo 2. In another terminal run:
echo iex $COOKIE_ARGS  --name me@$DOMAIN -S mix run --no-start
echo
echo 3. Paste:
echo Node.connect ":'$APP@$DOMAIN'"
echo

echo Running tunnel now....
ssh -L 4369:localhost:4369 -L $PORT:localhost:$PORT $HOST

