# Dev only: compiled only in the dev environment, like its route in router.ex
if Mix.env() == :dev do
  defmodule ProcaWeb.DevTargetsController do
    @moduledoc """
    Dev only: serves a campaign's targets at `/t/<campaign name>.json` in the same
    format as the published lists on https://widget.proca.app/t/<campaign>.json,
    so a locally served MTT widget can load them from this server. Point the
    widget at it with `config.component.email.listUrl`.

    In production the lists are generated by the widget repo (`bin/target.js
    --publish`); this builds a simplified version straight from the DB.

    Unlike the published lists, this one includes the targets' emails (they are
    seeded dummies), so the widget's mailto mode (`email.server: false`) works.
    """
    use ProcaWeb, :controller

    import Ecto.Query
    alias Proca.{Repo, Campaign, Target}

    @salutations %{
      "en" => "Dear",
      "fr" => "Madame, Monsieur",
      "de" => "Sehr geehrte/r",
      "it" => "Gentile",
      "es" => "Estimado/a",
      "pl" => "Szanowna Pani / Szanowny Panie",
      "nl" => "Geachte",
      "pt" => "Caro/a"
    }

    def show(conn, %{"file" => file}) do
      name = String.replace_suffix(file, ".json", "")

      case Repo.get_by(Campaign, name: name) do
        nil ->
          conn |> put_status(404) |> json(%{error: "no campaign named #{name}"})

        campaign ->
          targets =
            from(t in Target,
              where: t.campaign_id == ^campaign.id,
              order_by: t.name,
              preload: :emails
            )
            |> Repo.all()
            |> Enum.map(&public_target/1)

          json(conn, targets)
      end
    end

    defp public_target(%Target{} = t) do
      locale = t.locale || "en"

      # fields are public by design, so they go out as-is
      Map.merge(t.fields || %{}, %{
        "procaid" => t.id,
        "externalId" => t.external_id,
        "name" => t.name,
        "country" => t.area && String.downcase(t.area),
        "area" => t.area,
        "locale" => locale,
        "lang" => locale,
        "description" => t.fields["party"] || t.fields["title"] || "",
        "salutation" => "#{Map.get(@salutations, locale, "Dear")} #{t.name},",
        "email" => t.emails |> Enum.map(& &1.email) |> Enum.join(","),
        "emails" => Enum.map(t.emails, &%{"email" => &1.email, "emailStatus" => &1.email_status})
      })
    end
  end
end
