export * as widget from './queries/widget'
export * as admin from './queries/admin'
export {basicAuth, tokenAuth, BasicAuth, TokenAuth} from './auth'
export {link, httpLink, request, subscribe} from './client'
export * as types from './types'
