#!/bin/bash

set -u 
set -e 

if [ $# -lt 2 ]; then
  echo ads user to org by email, as coordinator
  echo or makes an existing user a coordinator.
  echo $0 email orgname
  exit 1
fi 

email=$1
org=$2

echo "make $email coordinator of $org"
proca-live rpc "
  case Proca.Org.get_by_name(\"$org\")  do 
   nil -> IO.puts(\"Org not found\") 
   org -> case Proca.Staffer.Role.add_user_as(\"$email\", org, :coordinator) do 
     {:error, :not_found} -> IO.puts(\"User not found\") 
     ch -> ch |> Proca.Repo.insert_or_update!
   end
  end
"
