#!/bin/bash

set -u 
set -e 

if [ $# -lt 1 ]; then
  echo removes an org if no real action data present
  echo $0 orgname
  exit 1
fi 

org=$1

echo "delete $org"
proca-live rpc "
  case Proca.Org.get_by_name(\"$org\")  do 
   nil -> IO.puts(\"Org not found\") 
   org -> 
     Proca.Repo.preload(org, [:action_pages]).action_pages
     |> Enum.each(&Proca.Repo.delete!(&1))
     Proca.Repo.delete!(org)
  end
"
