#!/bin/bash

set -u 
set -e 

if [ $# -lt 1 ]; then
  echo reset user password in proca-server user db
  echo $0 email 
  exit 1
fi 

email=$1

echo "reset password for $email"
proca-live rpc "
  alias Proca.Users.User
  user = User.one(email: \"$email\") || throw :no_such_user
  {ch, p} = User.generate_password_changeset(user)
  Proca.Repo.update!(ch)
  IO.puts(p)
"
